services:
  api:
    build:
      context: .
    environment:
      DATABASE_URL: postgresql://postgres:password@host.docker.internal:5432/mydb?schema=public
    ports:
      - '3001:3000'
    depends_on:
      migration:
        condition: service_completed_successfully
  migration:
    build:
      context: .
    environment:
      DATABASE_URL: postgresql://postgres:password@host.docker.internal:5432/mydb?schema=public
    entrypoint: ['npx', 'prisma', 'migrate', 'deploy']
    depends_on:
      - postgis
  postgis:
    image: postgis/postgis
    ports:
      - '5432:5432'
    container_name: postgis
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      ALLOW_IP_RANGE: 0.0.0.0/0
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
