name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
      - name: Run pre-commit checks
        run: pnpm run lint:all

      - name: Run tests
        run: pnpm run test:check
